### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by Mte90** [naraesk/plasma-codeship#3]
In the readme there are no explanation about what put in the settings of the widget.
I have a project but with no branch so I am not sure about what insert.

**Comment by naraesk** [comment]
In the field title you can enter a title, it's just a name that will be displayed.
In the field project UUID you have to enter your project uuid from codeship.

Branch is the branch of the repository you build. What exactly do you build that you do not have a branch?

**Comment by Mte90** [comment]
You are right, I was using the id of the project and not he id that can be found on settings page of the project and saved the branch `master`.
Now I see that in the list :-)
